camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Admin
    email: admin@admin.com
  filter:
    create: All tasks

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
    host: smtp.gmail.com
    username: naucna.centrala28@gmail.com
    password: centrala28
    port: 587

